PickPlaz ESP32-C3 Port: /home/asterion/3D/pick-plaz/pickplazfeederstm_ESP32Port/ESP32Port/pickplazESP32Port/src/hal.c File Reference
hal.c File Reference
Implements the ESP32-C3 hardware abstraction layer.
#include "hal.h"
#include "hal_config.h"
#include "esp_err.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "driver/gpio.h"
#include "driver/i2c.h"
#include "driver/ledc.h"
#include "driver/spi_master.h"
#include "driver/uart.h"
#include "esp_adc/adc_oneshot.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
Macros
#define HAL_TIMER_MAX 4
Defines the maximum number of HAL timer slots.
Functions
hal_status_t hal_adc_init (void)
Initializes the ADC oneshot unit.
int hal_adc_read (int channel)
Reads a raw ADC sample from the specified channel.
void hal_delay_ms (uint32_t ms)
Delays execution for the requested number of milliseconds.
hal_status_t hal_gpio_config_input (int pin, hal_gpio_pull_t pull)
Configures a GPIO pin as an input with pull settings.
hal_status_t hal_gpio_config_output (int pin, hal_gpio_level_t initial_level)
Configures a GPIO pin as a push-pull output.
hal_gpio_level_t hal_gpio_read (int pin)
Reads the current logic level of a GPIO.
hal_status_t hal_gpio_write (int pin, hal_gpio_level_t level)
Writes a logic level to a GPIO output.
hal_status_t hal_i2c_init (int bus_id, uint32_t clock_hz)
Initializes the I2C master bus.
int hal_i2c_read (int bus_id, uint8_t addr, uint8_t *data, size_t length)
Reads data from an I2C device.
int hal_i2c_write (int bus_id, uint8_t addr, const uint8_t *data, size_t length)
Writes data to an I2C device.
hal_status_t hal_init (void)
Initializes HAL services.
hal_status_t hal_pwm_init (int channel, int pin, uint32_t freq_hz, uint32_t duty_resolution_bits)
Initializes a PWM channel for a GPIO pin.
hal_status_t hal_pwm_set_duty (int channel, uint32_t duty)
Updates the PWM duty for a configured channel.
void hal_selftest_run (void)
Runs a basic HAL self-test sequence.
hal_status_t hal_spi_init (int bus_id, uint32_t clock_hz, uint8_t mode)
Initializes the SPI bus and device handle.
int hal_spi_transfer (int bus_id, const uint8_t *tx, uint8_t *rx, size_t length)
Performs a blocking SPI transfer.
hal_status_t hal_tick_start (uint32_t hz, hal_timer_callback_t callback, void *user_data)
Starts the global HAL tick timer.
hal_status_t hal_tick_stop (void)
Stops the global HAL tick timer.
hal_status_t hal_timer_start (int timer_id, uint32_t period_ms, hal_timer_callback_t callback, void *user_data)
Starts a periodic HAL timer.
hal_status_t hal_timer_stop (int timer_id)
Stops a periodic HAL timer.
hal_status_t hal_uart_init (int uart_id, uint32_t baud_rate)
Initializes UART0 with the configured pins.
int hal_uart_read (int uart_id, uint8_t *data, size_t length)
Reads data from UART0.
int hal_uart_write (int uart_id, const uint8_t *data, size_t length)
Writes data to UART0.
Detailed Description
Implements the ESP32-C3 hardware abstraction layer.
Provides GPIO, timers, PWM, UART, SPI, I2C, ADC, and optional self-test services using ESP-IDF drivers. The HAL hides platform specifics from the application layer.
Thread-safety:
Not thread-safe; callers should serialize access when sharing resources.
Definition in file hal.c.
Macro Definition Documentation
HAL_TIMER_MAX
#define HAL_TIMER_MAX 4
Defines the maximum number of HAL timer slots.
Limits the number of concurrent periodic timers that can be registered via hal_timer_start().
Definition at line 211 of file hal.c.
Referenced by hal_timer_start(), and hal_timer_stop().
Function Documentation
hal_adc_init()
hal_status_t hal_adc_init (void)
Initializes the ADC oneshot unit.
Uses ADC_UNIT_1 and prepares it for per-channel configuration.
Postconditions:
ADC oneshot handle is available.
Side effects:
Allocates ADC unit resources.
Returns
HAL_OK on success, HAL_ERR_INVALID on initialization failure.
Definition at line 910 of file hal.c.
Referenced by hal_adc_read(), and pickplaz_app_init().
hal_adc_read()
int hal_adc_read (int channel)
Reads a raw ADC sample from the specified channel.
Configures channel attenuation and bit width on each read to match the default ESP-IDF oneshot configuration.
Preconditions:
channel must be a valid ADC channel for ADC_UNIT_1.
Parameters
channel ADC channel number.
Returns
Raw ADC reading on success, HAL_ERR_INVALID on failure, HAL_ERR_UNSUPPORTED if channel is disabled.
Definition at line 940 of file hal.c.
References hal_adc_init().
Referenced by hal_selftest_run().
hal_delay_ms()
void hal_delay_ms (uint32_t ms)
Delays execution for the requested number of milliseconds.
Uses the FreeRTOS tick delay to suspend the calling task.
Preconditions:
Must be called from a task context (not an ISR).
Side effects:
Suspends the current task.
Parameters
ms Delay duration in milliseconds. Zero performs no delay.
Definition at line 84 of file hal.c.
Referenced by hal_selftest_run().
hal_gpio_config_input()
hal_status_t hal_gpio_config_input (int pin, hal_gpio_pull_t pull)
Configures a GPIO pin as an input with pull settings.
Sets the pin to input mode and enables the requested pull-up or pull-down.
Preconditions:
pin must be a valid GPIO.
Postconditions:
GPIO is configured for input with the requested pull configuration.
Side effects:
Updates GPIO hardware configuration.
Parameters
pin GPIO number to configure.
pull Pull mode (none/up/down).
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid pin/config failure.
Definition at line 149 of file hal.c.
Referenced by hal_selftest_run().
hal_gpio_config_output()
hal_status_t hal_gpio_config_output (int pin, hal_gpio_level_t initial_level)
Configures a GPIO pin as a push-pull output.
Sets the pin to output mode with no pull resistors and applies the initial logic level.
Preconditions:
pin must be a valid output-capable GPIO.
Postconditions:
GPIO is configured for output and driven to initial_level.
Side effects:
Updates GPIO hardware configuration.
Parameters
pin GPIO number to configure.
initial_level Initial logic level to drive.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid pin/config failure.
Definition at line 111 of file hal.c.
Referenced by hal_selftest_run().
hal_gpio_read()
hal_gpio_level_t hal_gpio_read (int pin)
Reads the current logic level of a GPIO.
Returns HAL_GPIO_LOW if the pin is invalid.
Parameters
pin GPIO number to read.
Returns
HAL_GPIO_HIGH or HAL_GPIO_LOW based on the sampled level.
Definition at line 197 of file hal.c.
Referenced by hal_selftest_run().
hal_gpio_write()
hal_status_t hal_gpio_write (int pin, hal_gpio_level_t level)
Writes a logic level to a GPIO output.
Preconditions:
pin must be configured as an output-capable GPIO.
Side effects:
Updates the GPIO output level.
Parameters
pin GPIO number to write.
level Logic level to drive.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid pin.
Definition at line 180 of file hal.c.
Referenced by hal_selftest_run().
hal_i2c_init()
hal_status_t hal_i2c_init (int bus_id, uint32_t clock_hz)
Initializes the I2C master bus.
Only I2C_NUM_0 is supported. Pins are defined in hal_config.h.
Preconditions:
bus_id must be I2C_NUM_0.
SDA/SCL pins must be configured and valid.
Postconditions:
I2C driver is installed and ready for transfers.
Side effects:
Allocates I2C driver resources.
Parameters
bus_id I2C bus identifier (must be I2C_NUM_0).
clock_hz Bus clock in Hertz. Zero uses HAL_I2C0_CLOCK_HZ.
Returns
HAL_OK on success, HAL_ERR_UNSUPPORTED on unsupported config, HAL_ERR_INVALID on invalid parameters or driver failure.
Definition at line 693 of file hal.c.
Referenced by hal_i2c_read(), hal_i2c_write(), and hal_selftest_run().
hal_i2c_read()
int hal_i2c_read (int bus_id, uint8_t addr, uint8_t * data, size_t length)
Reads data from an I2C device.
Uses a blocking transfer with a 100 ms timeout.
Preconditions:
I2C bus has been initialized.
Parameters
bus_id I2C bus identifier (must be I2C_NUM_0).
addr 7-bit I2C device address.
data Output buffer. Must not be NULL.
length Number of bytes to read. Must be > 0.
Returns
Number of bytes read, or HAL_ERR_INVALID on failure, HAL_ERR_UNSUPPORTED if the bus is not available.
Definition at line 771 of file hal.c.
References hal_i2c_init().
hal_i2c_write()
int hal_i2c_write (int bus_id, uint8_t addr, const uint8_t * data, size_t length)
Writes data to an I2C device.
Uses a blocking transfer with a 100 ms timeout.
Preconditions:
I2C bus has been initialized.
Parameters
bus_id I2C bus identifier (must be I2C_NUM_0).
addr 7-bit I2C device address.
data Buffer to write. Must not be NULL.
length Number of bytes to write. Must be > 0.
Returns
Number of bytes written, or HAL_ERR_INVALID on failure, HAL_ERR_UNSUPPORTED if the bus is not available.
Definition at line 743 of file hal.c.
References hal_i2c_init().
hal_init()
hal_status_t hal_init (void)
Initializes HAL services.
Performs lightweight HAL startup and logs the initialization banner.
Postconditions:
HAL services are available to callers.
Side effects:
Writes a log message.
Returns
HAL_OK on success.
Definition at line 65 of file hal.c.
Referenced by app_main().
hal_pwm_init()
hal_status_t hal_pwm_init (int channel, int pin, uint32_t freq_hz, uint32_t duty_resolution_bits)
Initializes a PWM channel for a GPIO pin.
Configures the LEDC timer and channel for the requested frequency and resolution. Motor pins are placed on a separate LEDC timer to preserve frequency settings.
Preconditions:
channel must be in [0, LEDC_CHANNEL_MAX).
pin must be a valid output-capable GPIO.
Postconditions:
The PWM channel is configured and ready for duty updates.
Side effects:
Allocates/updates LEDC timer and channel configuration.
Parameters
channel LEDC channel index.
pin GPIO number to drive with PWM.
freq_hz PWM frequency in Hertz.
duty_resolution_bits Duty resolution in bits.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid params or failure.
Definition at line 474 of file hal.c.
Referenced by hal_selftest_run().
hal_pwm_set_duty()
hal_status_t hal_pwm_set_duty (int channel, uint32_t duty)
Updates the PWM duty for a configured channel.
Clamps duty to the configured maximum for the channel before updating.
Preconditions:
channel must be configured via hal_pwm_init().
Side effects:
Updates LEDC duty and commits it to hardware.
Parameters
channel LEDC channel index.
duty Duty value in channel resolution units.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid params or failure, HAL_ERR_UNSUPPORTED if the channel is not configured.
Definition at line 545 of file hal.c.
Referenced by hal_selftest_run().
hal_selftest_run()
void hal_selftest_run (void)
Runs a basic HAL self-test sequence.
Validates GPIO, tick timer, PWM, and optional peripheral bring-up. Only compiled when HAL_SELFTEST is defined.
Side effects:
Reconfigures GPIO/PWM peripherals for test patterns.
Writes test output to the UART when available.
Note
Intended for development builds only.
Definition at line 980 of file hal.c.
References hal_adc_read(), hal_delay_ms(), hal_gpio_config_input(), hal_gpio_config_output(), hal_gpio_read(), hal_gpio_write(), hal_i2c_init(), hal_pwm_init(), hal_pwm_set_duty(), hal_spi_init(), hal_tick_start(), hal_tick_stop(), hal_uart_init(), and hal_uart_write().
Referenced by app_main().
hal_spi_init()
hal_status_t hal_spi_init (int bus_id, uint32_t clock_hz, uint8_t mode)
Initializes the SPI bus and device handle.
Only bus_id 0 is supported and mapped to SPI2_HOST. Pins are defined in hal_config.h.
Preconditions:
SPI pins must be configured and valid.
Postconditions:
SPI bus is initialized and device handle is ready.
Side effects:
Allocates SPI bus resources.
Parameters
bus_id SPI bus identifier (must be 0).
clock_hz Clock rate in Hertz. Zero uses HAL_SPI0_CLOCK_HZ.
mode SPI mode (0-3).
Returns
HAL_OK on success, HAL_ERR_UNSUPPORTED on unsupported config, HAL_ERR_INVALID on invalid parameters or driver failure.
Definition at line 815 of file hal.c.
Referenced by hal_selftest_run(), and hal_spi_transfer().
hal_spi_transfer()
int hal_spi_transfer (int bus_id, const uint8_t * tx, uint8_t * rx, size_t length)
Performs a blocking SPI transfer.
Sends tx bytes (if provided) and optionally captures rx bytes.
Preconditions:
SPI bus has been initialized.
Parameters
bus_id SPI bus identifier (must be 0).
tx Optional transmit buffer (may be NULL).
rx Optional receive buffer (may be NULL).
length Number of bytes to transfer. Must be > 0.
Returns
Number of bytes transferred, or HAL_ERR_INVALID on failure, HAL_ERR_UNSUPPORTED if the bus is not available.
Definition at line 875 of file hal.c.
References hal_spi_init().
hal_tick_start()
hal_status_t hal_tick_start (uint32_t hz, hal_timer_callback_t callback, void * user_data)
Starts the global HAL tick timer.
Configures a periodic ESP timer that calls the provided callback at the requested frequency.
Preconditions:
hz must be > 0.
callback must be non-null.
Postconditions:
The tick callback is invoked at approximately hz.
Side effects:
Allocates and starts an ESP timer.
Parameters
hz Tick frequency in Hertz.
callback Function to invoke on each tick. Must not be NULL.
user_data Opaque pointer passed to callback.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid params or failure.
Definition at line 357 of file hal.c.
Referenced by hal_selftest_run().
hal_tick_stop()
hal_status_t hal_tick_stop (void)
Stops the global HAL tick timer.
Cancels and deletes the tick timer if it is active.
Postconditions:
The global tick timer is inactive.
Side effects:
Deletes the underlying ESP timer.
Returns
HAL_OK on success.
Definition at line 409 of file hal.c.
Referenced by hal_selftest_run(), and pickplaz_app_stop().
hal_timer_start()
hal_status_t hal_timer_start (int timer_id, uint32_t period_ms, hal_timer_callback_t callback, void * user_data)
Starts a periodic HAL timer.
Allocates or reuses a timer slot and calls the provided callback at the specified period.
Preconditions:
timer_id must be in range [0, HAL_TIMER_MAX).
callback must be non-null.
period_ms must be > 0.
Postconditions:
The timer slot is active and invokes callback periodically.
Side effects:
Allocates an ESP timer and schedules periodic callbacks.
Parameters
timer_id Timer slot identifier.
period_ms Period in milliseconds.
callback Function to invoke each period. Must not be NULL.
user_data Opaque pointer passed to callback.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid parameters or failure.
Definition at line 252 of file hal.c.
References HAL_TIMER_MAX.
hal_timer_stop()
hal_status_t hal_timer_stop (int timer_id)
Stops a periodic HAL timer.
Cancels and deletes the timer slot if it is active.
Preconditions:
timer_id must be in range [0, HAL_TIMER_MAX).
Postconditions:
The timer slot is inactive.
Side effects:
Deletes the underlying ESP timer if present.
Parameters
timer_id Timer slot identifier.
Returns
HAL_OK on success, HAL_ERR_INVALID on invalid timer_id.
Definition at line 306 of file hal.c.
References HAL_TIMER_MAX.
hal_uart_init()
hal_status_t hal_uart_init (int uart_id, uint32_t baud_rate)
Initializes UART0 with the configured pins.
Only UART0 is supported. Pins are defined in hal_config.h and must be set to non-BOARD_GPIO_UNUSED to enable UART usage.
Preconditions:
uart_id must be UART_NUM_0.
UART pins must be configured in hal_config.h.
Postconditions:
UART driver is installed and ready for IO.
Side effects:
Allocates UART driver resources.
Parameters
uart_id UART identifier (must be UART_NUM_0).
baud_rate Baud rate in bits per second.
Returns
HAL_OK on success, HAL_ERR_UNSUPPORTED on unsupported config, HAL_ERR_INVALID on invalid parameters or driver failure.
Definition at line 589 of file hal.c.
Referenced by hal_selftest_run().
hal_uart_read()
int hal_uart_read (int uart_id, uint8_t * data, size_t length)
Reads data from UART0.
Performs a non-blocking read with zero timeout.
Preconditions:
UART0 has been initialized.
Parameters
uart_id UART identifier (must be UART_NUM_0).
data Output buffer. Must not be NULL.
length Maximum number of bytes to read. Must be > 0.
Returns
Number of bytes read, or HAL_ERR_INVALID on invalid params.
Definition at line 663 of file hal.c.
hal_uart_write()
int hal_uart_write (int uart_id, const uint8_t * data, size_t length)
Writes data to UART0.
Preconditions:
UART0 has been initialized.
Side effects:
Sends bytes over the UART driver.
Parameters
uart_id UART identifier (must be UART_NUM_0).
data Buffer to write. Must not be NULL.
length Number of bytes to write. Must be > 0.
Returns
Number of bytes written, or HAL_ERR_INVALID on invalid params.
Definition at line 642 of file hal.c.
Referenced by hal_selftest_run().