PickPlaz ESP32-C3 Port: /home/asterion/3D/pick-plaz/pickplazfeederstm_ESP32Port/ESP32Port/pickplazESP32Port/src/pickplaz_app.c File Reference
pickplaz_app.c File Reference
Implements the PickPlaz application state machine and IO orchestration.
#include "pickplaz_app.h"
#include <inttypes.h>
#include "board_pins.h"
#include "esp_log.h"
#include "hal.h"
#include "hal_config.h"
Enumerations
enum app_constants {
APP_PWM_STM32_MAX = 2048 , APP_TICK_HZ = 1000 , APP_SINE_LEN = 256 , APP_SINE_SCALE = 8 ,
APP_FEED_PULSE_MS = 500 , APP_BUTTON_CNT_MAX = 20 , APP_BUTTON_LONGPRESS = 400
}
Application timing and scaling constants.
enum app_pwm_channels {
APP_PWM_LED0_CH = 0 , APP_PWM_LED1_CH = 1 , APP_PWM_LED2_CH = 2 , APP_PWM_LED3_CH = 3 ,
APP_PWM_MOTOR_IN1_CH = 4 , APP_PWM_MOTOR_IN2_CH = 5
}
PWM channel assignments for LEDs and motor outputs.
enum app_state_t {
APP_init , APP_idle , APP_increment_forward1 , APP_increment_backward1 ,
APP_increment_forward2 , APP_increment_backward2 , APP_free_forward , APP_free_backward
}
Represents the main application state machine.
enum button_event_t { BUTTON_none , BUTTON_short , BUTTON_long , BUTTON_hold }
Represents the debounced button event for a single tick.
enum feed_fsm_t { FEED_fsm_low , FEED_fsm_high }
Tracks the raw feed input level for pulse detection.
enum feed_signal_t { FEED_none , FEED_short , FEED_long }
Represents a decoded feed input event.
enum motor_pwm_constants {
MOTOR_FORWARD_NORMAL = 2048 , MOTOR_BACKWARD_NORMAL = -2048 , MOTOR_FORWARD_FAST = 2048 , MOTOR_BACKWARD_FAST = -2048 ,
MOTOR_STOP = 0
}
PWM values for motor control modes.
enum motor_state_t {
MOTOR_init , MOTOR_idle , MOTOR_running_forward , MOTOR_running_backward ,
MOTOR_brake
}
Describes the motor control state machine.
Functions
hal_status_t pickplaz_app_init (void)
Initializes PickPlaz application state and IO.
hal_status_t pickplaz_app_start (void)
Starts the PickPlaz application tick.
void pickplaz_app_stop (void)
Stops the PickPlaz application tick.
Variables
const uint16_t sintab [256]
Provides a 256-entry sine lookup table for LED animation.
Detailed Description
Implements the PickPlaz application state machine and IO orchestration.
Owns the 1 kHz application tick, translates button/opto/feed inputs into state transitions, and drives LED/motor outputs through the HAL. This module is platform-agnostic and relies on board pin mappings defined in board_pins.h plus optional overrides in hal_config.h.
Thread-safety:
Not thread-safe; intended to run from a single periodic tick.
Definition in file pickplaz_app.c.
Enumeration Type Documentation
app_constants
enum app_constants
Application timing and scaling constants.
Definition at line 49 of file pickplaz_app.c.
app_pwm_channels
enum app_pwm_channels
PWM channel assignments for LEDs and motor outputs.
Definition at line 172 of file pickplaz_app.c.
app_state_t
enum app_state_t
Represents the main application state machine.
States mirror the STM32 firmware behavior for indexed moves and continuous motion while a button is held.
Enumerator
APP_init
Initial state after reset.
APP_idle
Idle state waiting for button or feed events.
APP_increment_forward1
Forward step: move until the opto leaves index or timeout.
APP_increment_backward1
Reverse step: move until the opto leaves index or timeout.
APP_increment_forward2
Forward step: continue until opto returns to index or timeout.
APP_increment_backward2
Reverse step: continue until opto returns to index or timeout.
APP_free_forward
Continuous forward motion while the forward request is held.
APP_free_backward
Continuous reverse motion while the reverse request is held.
Definition at line 111 of file pickplaz_app.c.
button_event_t
enum button_event_t
Represents the debounced button event for a single tick.
Enumerator
BUTTON_none
No event this tick.
BUTTON_short
Short press released after debounce timing.
BUTTON_long
Long press released after exceeding the long-press threshold.
BUTTON_hold
Button remains held; emitted while pressed.
Definition at line 133 of file pickplaz_app.c.
feed_fsm_t
enum feed_fsm_t
Tracks the raw feed input level for pulse detection.
Enumerator
FEED_fsm_low
Feed input is low; waiting for a rising edge.
FEED_fsm_high
Feed input is high; timing the pulse width.
Definition at line 78 of file pickplaz_app.c.
feed_signal_t
enum feed_signal_t
Represents a decoded feed input event.
The feed input is sampled at 1 kHz and converted into a short or long event consumed by the application FSM.
Enumerator
FEED_none
No feed event has been detected.
FEED_short
A short feed pulse was latched.
FEED_long
A long feed pulse was latched.
Definition at line 66 of file pickplaz_app.c.
motor_pwm_constants
enum motor_pwm_constants
PWM values for motor control modes.
Definition at line 161 of file pickplaz_app.c.
motor_state_t
enum motor_state_t
Describes the motor control state machine.
Tracks whether the motor is idle, running, or in active braking.
Enumerator
MOTOR_init
Initial state after reset; forces outputs to a stopped condition.
MOTOR_idle
Motor is stopped and waiting for a target.
MOTOR_running_forward
Motor is driving forward with PWM.
MOTOR_running_backward
Motor is driving backward with PWM.
MOTOR_brake
Motor is actively braking after a stop request.
Definition at line 91 of file pickplaz_app.c.
Function Documentation
pickplaz_app_init()
hal_status_t pickplaz_app_init (void)
Initializes PickPlaz application state and IO.
Configures PWM outputs, input GPIOs, and optional ADC usage, then resets all application state machines and counters.
Preconditions:
hal_init() has been called.
Postconditions:
Application state machines are reset to APP_init/MOTOR_init.
GPIO/PWM resources are configured for enabled pins.
Side effects:
Configures PWM, GPIO, and ADC resources through the HAL.
Logs initialization status.
Error handling:
Returns HAL_OK; initialization failures are reported via HAL logs.
Returns
HAL_OK on completion.
Definition at line 843 of file pickplaz_app.c.
References APP_init, FEED_fsm_low, FEED_none, hal_adc_init(), and MOTOR_init.
Referenced by app_main().
pickplaz_app_start()
hal_status_t pickplaz_app_start (void)
Starts the PickPlaz application tick.
Registers the 1 kHz tick callback with the HAL timer service.
Preconditions:
pickplaz_app_init() has been called.
Postconditions:
The application tick is running.
Side effects:
Allocates and starts a periodic timer via the HAL.
Error handling:
Returns HAL_ERR_* codes from hal_tick_start().
Returns
HAL_OK on success, or a HAL_ERR_* code on failure.
Definition at line 891 of file pickplaz_app.c.
Referenced by app_main().
pickplaz_app_stop()
void pickplaz_app_stop (void)
Stops the PickPlaz application tick.
Cancels the periodic tick timer created by pickplaz_app_start().
Side effects:
Stops the periodic timer via the HAL.
Definition at line 904 of file pickplaz_app.c.
References hal_tick_stop().
Variable Documentation
sintab
const uint16_t sintab[256] extern
Provides a 256-entry sine lookup table for LED animation.
Values range from 0..256 and are scaled by APP_SINE_SCALE to reach the STM32-style 0..APP_PWM_STM32_MAX duty range.
Note
Indexed modulo APP_SINE_LEN.
Definition at line 12 of file sintab.c.