/*
 * PickPlaz ESP32-C3 Port
 * Copyright (c) 2026 Asterion Daedalus https://github.com/Bazmundi
 * SPDX-License-Identifier: MIT
 *
 * This file is part of PickPlaz ESP32-C3 Port and is licensed under the MIT License.
 * See the LICENSE file in the project root for full license text.
 */

#ifndef PICKPLAZ_BOARD_PINS_H_
#define PICKPLAZ_BOARD_PINS_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#define BOARD_GPIO_UNUSED (-1)

#define BOARD_GPIO_LED0_DEFAULT 0
#define BOARD_GPIO_LED1_DEFAULT 1
#define BOARD_GPIO_LED2_DEFAULT 3
#define BOARD_GPIO_LED3_DEFAULT 5
#define BOARD_GPIO_LED4_DEFAULT 10
#define BOARD_GPIO_MOTOR_IN1_DEFAULT 6
#define BOARD_GPIO_MOTOR_IN2_DEFAULT 7
#define BOARD_GPIO_BUTTON_FWD_DEFAULT 20
#define BOARD_GPIO_BUTTON_REV_DEFAULT 21
#define BOARD_GPIO_OPTO_INT_DEFAULT 4

#ifdef PICKPLAZ_QEMU_PINMAP
#define BOARD_GPIO_LED0 BOARD_GPIO_UNUSED
#define BOARD_GPIO_LED1 BOARD_GPIO_UNUSED
#define BOARD_GPIO_LED2 BOARD_GPIO_LED2_DEFAULT
#define BOARD_GPIO_LED3 BOARD_GPIO_LED3_DEFAULT
#define BOARD_GPIO_LED4 BOARD_GPIO_LED4_DEFAULT
#define BOARD_GPIO_MOTOR_IN1 BOARD_GPIO_MOTOR_IN1_DEFAULT
#define BOARD_GPIO_MOTOR_IN2 BOARD_GPIO_MOTOR_IN2_DEFAULT
#define BOARD_GPIO_BUTTON_FWD BOARD_GPIO_LED0_DEFAULT
#define BOARD_GPIO_BUTTON_REV BOARD_GPIO_LED1_DEFAULT
#define BOARD_GPIO_OPTO_INT BOARD_GPIO_OPTO_INT_DEFAULT
#else
#define BOARD_GPIO_LED0 BOARD_GPIO_LED0_DEFAULT
#define BOARD_GPIO_LED1 BOARD_GPIO_LED1_DEFAULT
#define BOARD_GPIO_LED2 BOARD_GPIO_LED2_DEFAULT
#define BOARD_GPIO_LED3 BOARD_GPIO_LED3_DEFAULT
#define BOARD_GPIO_LED4 BOARD_GPIO_LED4_DEFAULT
#define BOARD_GPIO_MOTOR_IN1 BOARD_GPIO_MOTOR_IN1_DEFAULT
#define BOARD_GPIO_MOTOR_IN2 BOARD_GPIO_MOTOR_IN2_DEFAULT
#define BOARD_GPIO_BUTTON_FWD BOARD_GPIO_BUTTON_FWD_DEFAULT
#define BOARD_GPIO_BUTTON_REV BOARD_GPIO_BUTTON_REV_DEFAULT
#define BOARD_GPIO_OPTO_INT BOARD_GPIO_OPTO_INT_DEFAULT
#endif

#define BOARD_BUTTON_ACTIVE_LOW 1

#ifdef __cplusplus
}
#endif

#endif
